parameters:
  - name: projectName
    type: string
    default: ""
  - name: version
    type: string
    default: "$(Build.BuildNumber)"

steps:
  - task: Npm@1
    displayName: Install Dependencies
    inputs:
      command: install
      workingDir: ./
  - task: PowerShell@2
    displayName: Get Angular Version
    inputs:
      targetType: inline
      script: |
        $angularVersion = npm list @angular/core --depth=0 | select-string 'angular/core@(\d{1,3})' | ForEach-Object { $_.Matches[0].Groups[1].Value }
        Write-Host "Angular version is $angularVersion"
        Write-Host "##vso[task.setvariable variable=version;]${angularVersion}.${{ parameters.version }}"
        Write-Host "##vso[build.updatebuildnumber]${angularVersion}.${{ parameters.version }}"
  - task: FileTransform@1
    displayName: Transform Version In package.json
    inputs:
      folderPath: $(System.DefaultWorkingDirectory)/projects/${{ parameters.projectName }}
      fileType: json
      targetFiles: package.json
  - task: Npm@1
    displayName: Lint Project
    inputs:
      command: custom
      workingDir: ./
      customCommand: run lint ${{ parameters.projectName }}
  - task: Npm@1
    displayName: Build Project
    inputs:
      command: custom
      workingDir: ./
      customCommand: run build ${{ parameters.projectName }}
  - task: PublishPipelineArtifact@1
    displayName: Publish Pipeline Artifact
    inputs:
      targetPath: ./dist/${{ parameters.projectName }}
      artifactName: ${{ parameters.projectName }}
