name: $(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.r)

variables:
  version: $(Build.BuildNumber)

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: FileTransform@1
  inputs:
    folderPath: '$(System.DefaultWorkingDirectory)/projects/diflexmo-angular-design/'
    fileType: 'json'
    targetFiles: 'package.json'
- task: Npm@1
  inputs:
    command: 'install'
    workingDir: './'
- task: Npm@1
  inputs:
    command: 'install'
    workingDir: './projects/diflexmo-angular-design/'
- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: './'
    customCommand: 'run build diflexmo-angular-design'
- task: Npm@1
  inputs:
    command: 'publish'
    workingDir: './dist/diflexmo-angular-design'
    publishRegistry: 'useFeed'
    publishFeed: '18e540ed-207f-4a1e-8e3b-014618dd9c9a'