name: $(Year:yyyy)$(Month).$(DayOfMonth)$(Rev:.r)

variables:
  version: $(Build.BuildNumber)
  name: 'diflexmo-angular-design-dev'

trigger:
  - development

pool:
  vmImage: ubuntu-latest

steps:
  - task: FileTransform@1
    displayName: 'Transform package.json version'
    inputs:
      folderPath: '$(System.DefaultWorkingDirectory)/projects/diflexmo-angular-design/'
      fileType: 'json'
      targetFiles: 'package.json'
  - task: Npm@1
    displayName: 'Npm install workspace'
    inputs:
      command: 'install'
      workingDir: './'
  - task: Npm@1
    displayName: 'Npm install project'
    inputs:
      command: 'install'
      workingDir: './projects/diflexmo-angular-design/'
  - task: Npm@1
    displayName: 'Npm lint project'
    inputs:
      command: 'custom'
      workingDir: './'
      customCommand: 'run lint diflexmo-angular-design'
  - task: Npm@1
    displayName: 'Npm build'
    inputs:
      command: 'custom'
      workingDir: './'
      customCommand: 'run build diflexmo-angular-design'
  - task: Npm@1
    displayName: 'Npm publish'
    inputs:
      command: 'publish'
      workingDir: './dist/diflexmo-angular-design'
      publishRegistry: 'useFeed'
      publishFeed: '18e540ed-207f-4a1e-8e3b-014618dd9c9a'
