name: '$(Date:yyyyMMdd)$(Rev:.r)-rc'

variables:
  version: $(Build.BuildNumber)

trigger:
  - staging

pool:
  vmImage: ubuntu-latest

steps:
  - task: Npm@1
    displayName: 'Npm install workspace'
    inputs:
      command: 'install'
      workingDir: './'
  - task: Npm@1
    displayName: 'Npm install project'
    inputs:
      command: 'install'
      workingDir: './projects/diflexmo-angular-design/'
  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        $angularVersion = npm list @angular/core --depth=0 | select-string 'angular/core@(\d{1,3})' | ForEach-Object { $_.Matches[0].Groups[1].Value }
        Write-Host "Angular version is $angularVersion"
        Write-Host "##vso[task.setvariable variable=version;]${angularVersion}.$(Build.BuildNumber)"
        Write-Host "##vso[build.updatebuildnumber]${angularVersion}.$(Build.BuildNumber)"
  - task: FileTransform@1
    displayName: 'Transform package.json version'
    inputs:
      folderPath: '$(System.DefaultWorkingDirectory)/projects/diflexmo-angular-design/'
      fileType: 'json'
      targetFiles: 'package.json'
  - task: Npm@1
    displayName: 'Npm lint project'
    inputs:
      command: 'custom'
      workingDir: './'
      customCommand: 'run lint diflexmo-angular-design'
  - task: Npm@1
    displayName: 'Npm build'
    inputs:
      command: 'custom'
      workingDir: './'
      customCommand: 'run build diflexmo-angular-design'
  - task: Npm@1
    displayName: 'Npm publish'
    inputs:
      command: 'custom'
      workingDir: './dist/diflexmo-angular-design'
      customRegistry: 'useFeed'
      customFeed: '18e540ed-207f-4a1e-8e3b-014618dd9c9a'
      customCommand: 'publish --tag prerelease'
