# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: ubuntu-latest

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $sourceBranch = "$(System.PullRequest.SourceBranch)"
      
      if($sourceBranch -ne "refs/heads/staging")
      {
          exit 1
      }
  displayName: 'Check if correct pre-deployment branch'
